### ISSUE TITLE
https://www.sqlite.org/2020/sqlite-autoconf-3340000.tar.gz breaks f-e-d-c

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub-infra/flatpak-external-data-checker#172]
Hi,

Apparently https://www.sqlite.org/2020/sqlite-autoconf-3340000.tar.gz completely breaks f-e-d-c.

```bash
❯ flatpak run org.flathub.flatpak-external-data-checker org.audacityteam.Audacity.yaml
+ 2021-05-08 10:25:47,902    INFO src.checker: Checking 6 external data items
+ 2021-05-08 10:25:47,903    INFO src.checker: Started check [1/6] wxWidgets (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:47,903    INFO src.checkers.gitchecker: Skipping source wxWidgets, commit is specified, but neither tag nor branch
+ 2021-05-08 10:25:47,903    INFO src.checker: Started check [2/6] ffmpeg-4.2.3.tar.xz (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:47,906    INFO src.checker: Started check [3/6] ffmpeg-4.2.3.tar.xz (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:47,907    INFO src.checker: Started check [4/6] sqlite-autoconf-3340000.tar.gz (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:47,908    INFO src.checker: Started check [5/6] chrpath-0.16.tar.gz (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:47,908    INFO src.checker: Started check [6/6] audacity.git (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:47,914 WARNING root: bwrap is not available
+ 2021-05-08 10:25:47,922    INFO src.checker: Finished check [1/6] wxWidgets (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:48,208    INFO src.checker: Finished check [2/6] audacity.git (from org.audacityteam.Audacity.yaml)
+ 2021-05-08 10:25:48,374    INFO src.checker: Finished check [3/6] chrpath-0.16.tar.gz (from org.audacityteam.Audacity.yaml)
Traceback (most recent call last):
  File "/app/lib/fedc/src/lib/utils.py", line 74, in _extract_timestamp
    return dt.datetime.strptime(date_str, "%a, %d %b %Y %H:%M:%S %Z")
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Wed, 20 Jan 2021 15:25:15 +0000' does not match format '%a, %d %b %Y %H:%M:%S %Z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/flatpak-external-data-checker", line 30, in <module>
    main()
  File "/app/lib/fedc/src/main.py", line 316, in main
    outdated_num, updated = asyncio.run(run_with_args(parse_cli_args()))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/lib/fedc/src/main.py", line 292, in run_with_args
    await manifest_checker.check(filter_type)
  File "/app/lib/fedc/src/checker.py", line 242, in check
    ext_data_checked = await asyncio.gather(*check_tasks)
  File "/app/lib/fedc/src/checker.py", line 198, in _check_data
    await checker.check(data)
  File "/app/lib/fedc/src/checkers/urlchecker.py", line 96, in check
    new_version = await utils.get_extra_data_info_from_url(
  File "/app/lib/fedc/src/lib/utils.py", line 130, in get_extra_data_info_from_url
    _extract_timestamp(info),
  File "/app/lib/fedc/src/lib/utils.py", line 76, in _extract_timestamp
    return dt.datetime.strptime(date_str, "%a, %d-%b-%Y %H:%M:%S %Z")
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Wed, 20 Jan 2021 15:25:15 +0000' does not match format '%a, %d-%b-%Y %H:%M:%S %Z'
```

----

Here is the block of the manifest from https://github.com/flathub/org.audacityteam.Audacity/blob/cd4d8ef8ce3f01800b45434bc401569155efe7d4/org.audacityteam.Audacity.yaml#L122-L137:

```yaml
  - name: sqlite
    # version bundled with runtime is missing the SQLITE_DBPAGE virtual table
    build-options:
      cflags: >
        -DSQLITE_ENABLE_COLUMN_METADATA=1
        -DSQLITE_SECURE_DELETE=1
        -DSQLITE_ENABLE_FTS3=1
        -DSQLITE_ENABLE_UNLOCK_NOTIFY=1
        -DSQLITE_ENABLE_DBPAGE_VTAB=1
        -DSQLITE_ENABLE_DBSTAT_VTAB=1
    config-opts:
      - --enable-fts5
    sources:
      - type: archive
        url: https://www.sqlite.org/2020/sqlite-autoconf-3340000.tar.gz
        sha256: bf6db7fae37d51754737747aaaf413b4d6b3b5fbacd52bdb2d0d6e5b2edd9aee
```

Removing that whole chunk does not reproduce the problem.

**Comment by gasinvein** [comment]
Looks like the webserver returns `Date` header with numeric UTC offset instead of the timezone name (`+0000` vs. `UTC`). Should be easy to fix, just handle another date string format in `utils._extract_timestamp`.
