### ISSUE TITLE
versions filter: failure when relational operation generate an empty list to target a future release

### ISSUE THREAD

**Issue by tinywrkb** [flathub-infra/flatpak-external-data-checker#240]
The scenario is that the module is need to be built from a specific commit, but soon as there's a new release then f-e-d-c should update the source.  

The problem is that the Anitya checker fails with the error `IndexError: list index out of range
` when adding a versions filter with a greater than operator, using the current last release as an operand.

I'm using an updated `org.flathub.flatpak-external-data-checker` app from Flathub.

Example module:
```
name: gnuradio-iqbal
buildsystem: cmake
sources:
  - type: git
    url: https://github.com/osmocom/gr-iqbal.git
    #tag: v0.38.2
    commit: fbee239a6fb36dd2fb564f6e6a0d393c4bc844db
    x-checker-data:
      type: anitya
      project-id: 14456
      stable-only: true
      versions:
        ">": 0.38.2
      tag-template: v$version
```

Log output:
```
INFO    src.checker: Started check [1/1] git gr-iqbal.git (from gnuradio-iqbal.yaml)
Traceback (most recent call last):
  File "/app/bin/flatpak-external-data-checker", line 30, in <module>
    main()
  File "/app/lib/fedc/src/main.py", line 395, in main
    outdated_num, errors_num, updated = asyncio.run(run_with_args(args))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/lib/fedc/src/main.py", line 356, in run_with_args
    await manifest_checker.check(args.filter_type)
  File "/app/lib/fedc/src/checker.py", line 341, in check
    ext_data_checked = await asyncio.gather(*check_tasks)
  File "/app/lib/fedc/src/checker.py", line 279, in _check_data
    await checker.check(data)
  File "/app/lib/fedc/src/checkers/anityachecker.py", line 58, in check
    latest_version = versions[0]
IndexError: list index out of range
```

**Comment by gasinvein** [comment]
Can you please provide a full manifest to test this with?

**Comment by tinywrkb** [comment]
This actually can be used as it is, just call it `gnuradio-iqbal.yaml`, and run f-e-d-c.

Or in a JSON format, which is more suited for shared-module usage.

`gnuradio-iqbal.json`

```
{
    "name": "gnuradio-iqbal",
    "buildsystem": "cmake",
    "sources": [
        {
            "type": "git",
            "url": "https://github.com/osmocom/gr-iqbal.git",
            "commit": "fbee239a6fb36dd2fb564f6e6a0d393c4bc844db",
            "x-checker-data": {
                "type": "anitya",
                "project-id": 14456,
                "stable-only": true,
                "versions": {
                    ">": "0.38.2"
                },
                "tag-template": "v$version"
            }
        }
    ]
}
```

If you really want something to build, then [this is my current WIP GNU Radio Flatpak manifest](https://github.com/tinywrkb/flatpaks/blob/master/org.gnuradio.gnuradio/org.gnuradio.gnuradio.yaml).

**Comment by tinywrkb** [comment]
@gasinvein Thanks for fixing this.
