### ISSUE TITLE
Gnome checker failing when parsing GHex dev releases

### ISSUE THREAD

**Issue by tinywrkb** [flathub-infra/flatpak-external-data-checker#284]
Another Gnome checker issue. I guess it doesn't like having Y as string in X.Y.Z release name, e.g. `4.alpha.1`.

```
name: ghex
buildsystem: meson
sources:
  - type: archive
    url: https://download.gnome.org/sources/ghex/3.41/ghex-3.41.0.tar.xz
    sha256: 29c746f22873b5e415bc3972dbd3dd60d6a51f7080e6a3e956c34d647ae344a2
    x-checker-data:
      type: gnome
      name: ghex
      stable-only: true
```

```
Traceback (most recent call last):
  File "/app/bin/flatpak-external-data-checker", line 30, in <module>
    main()
  File "/app/lib/fedc/src/main.py", line 440, in main
    outdated_num, errors_num, updated = asyncio.run(run_with_args(args))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/lib/fedc/src/main.py", line 403, in run_with_args
    await manifest_checker.check(args.filter_type)
  File "/app/lib/fedc/src/manifest.py", line 349, in check
    ext_data_checked = await asyncio.gather(*check_tasks)
  File "/app/lib/fedc/src/manifest.py", line 286, in _check_data
    await checker.check(data)
  File "/app/lib/fedc/src/checkers/gnomechecker.py", line 71, in check
    latest_version = list(filter(_is_stable, filtered_versions))[-1]
  File "/app/lib/fedc/src/checkers/gnomechecker.py", line 35, in _is_stable
    return (int(minor) % 2) == 0
ValueError: invalid literal for int() with base 10: 'alpha'
```

**Comment by gasinvein** [comment]
I wonder if there is any reasonable way to distinguish between the "old" and "new" gnome version schemes at all.

**Comment by bilelmoussaoui** [comment]
> I wonder if there is any reasonable way to distinguish between the "old" and "new" gnome version schemes at all.

Make it configurable?

**Comment by gasinvein** [comment]
> > I wonder if there is any reasonable way to distinguish between the "old" and "new" gnome version schemes at all.
> 
> Make it configurable?

Yeah, I guess we'll have to if there is no way to reliably auto-detect it.
