### ISSUE TITLE
Crashes on appdata update if no sources in top-level manifest

### ISSUE THREAD

**Issue by gasinvein** [flathub-infra/flatpak-external-data-checker#298]
Observed with [ElectronMail](https://github.com/flathub/com.github.vladimiry.ElectronMail/blob/eb1d8b7470fa7c214bb8bd629c704106e8e3f8ab/com.github.vladimiry.ElectronMail.yaml#L37-L43) flatpak, which has all its flatpak-builder modules in separate files:
```
2022-05-06T12:53:08.5105460Z INFO    src.manifest: Preparing to update appdata /github/workspace/flathub/com.github.vladimiry.ElectronMail/com.github.vladimiry.ElectronMail.metainfo.xml
2022-05-06T12:53:08.5122338Z Traceback (most recent call last):
2022-05-06T12:53:08.5122820Z   File "/app/flatpak-external-data-checker", line 30, in <module>
2022-05-06T12:53:08.5123091Z     main()
2022-05-06T12:53:08.5123310Z   File "/app/src/main.py", line 438, in main
2022-05-06T12:53:08.5123611Z     outdated_num, errors_num, updated = asyncio.run(run_with_args(args))
2022-05-06T12:53:08.5123940Z   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
2022-05-06T12:53:08.5124231Z     return loop.run_until_complete(main)
2022-05-06T12:53:08.5124555Z   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2022-05-06T12:53:08.5124847Z     return future.result()
2022-05-06T12:53:08.5125100Z   File "/app/src/main.py", line 406, in run_with_args
2022-05-06T12:53:08.5125392Z     changes = manifest_checker.update_manifests()
2022-05-06T12:53:08.5125701Z   File "/app/src/manifest.py", line 483, in update_manifests
2022-05-06T12:53:08.5125959Z     self._update_appdata()
2022-05-06T12:53:08.5126218Z   File "/app/src/manifest.py", line 432, in _update_appdata
2022-05-06T12:53:08.5126481Z     assert selected_data is not None
2022-05-06T12:53:08.5126699Z AssertionError
```

**Comment by tinywrkb** [comment]
My [userscripts extension for qutebrowser](https://github.com/flathub/flathub/pull/3070) is also affected by this. Maybe allow to disable metainfo updates via `flathub.json` property?

**Comment by gasinvein** [comment]
I think we should just avoid updating metainfo when there are no sources in the root manifest. In such case we have no reliable way to determine what's main app source anyway.

In the future, we can probably invent a more clever algorithm to associate a metainfo.xml file with a source (e.g. if they belong to the same module).

**Comment by bbhtt** [comment]
"Fixed" by https://github.com/flathub-infra/flatpak-external-data-checker/commit/cdabbc183267870feed0d4e8c7938274cac134d2

```
INFO    src.manifest: Loading module from module-gtk-cups-backend.yml
INFO    src.manifest: Loading module from module-gtk-settings.yaml
INFO    src.manifest: Loading module from module-libsecret.yaml
INFO    src.manifest: Loading module from module-squashfs.yaml
INFO    src.manifest: Loading module from module-zypak.yaml
INFO    src.manifest: Loading module from module-electron-mail.yaml
INFO    src.manifest: Checking 6 external data items
INFO    src.manifest: Started check [1/6] git gtk-cups-backend/gtk.git (from module-gtk-cups-backend.yml)
INFO    src.checkers.gitchecker: Skipping source gtk.git, not pinned to commit
INFO    src.manifest: Finished check [1/6] git gtk-cups-backend/gtk.git (from module-gtk-cups-backend.yml)
INFO    src.manifest: Skipped check [2/6] archive libsecret/libsecret-0.20.4.tar.gz (from module-libsecret.yaml)
INFO    src.manifest: Started check [3/6] git squashfs/squashfs-tools.git (from module-squashfs.yaml)
INFO    src.checkers.gitchecker: Skipping source squashfs-tools.git, commit is specified, but neither tag nor branch
INFO    src.manifest: Finished check [3/6] git squashfs/squashfs-tools.git (from module-squashfs.yaml)
INFO    src.manifest: Started check [4/6] git zypak/zypak (from module-zypak.yaml)
INFO    src.manifest: Skipped check [5/6] file electron-mail/electron-mail.snap (from module-electron-mail.yaml)
INFO    src.manifest: Skipped check [6/6] file electron-mail/electron-mail.deb (from module-electron-mail.yaml)
INFO    src.lib.externaldata: Source zypak: got new version 2024.01.17
INFO    src.manifest: Finished check [6/6] git zypak/zypak (from module-zypak.yaml)
OUTDATED: zypak
 Has a new version:
  URL:       https://github.com/refi64/zypak
  Commit:    ded79a2f8a509adc21834b95a9892073d4a91fdc
  Tag:       v2024.01.17
  Branch:    None
  Version:   2024.01.17
  Timestamp: None

INFO    src.manifest: Updating /home/bbhtt/Downloads/com.github.vladimiry.ElectronMail/module-zypak.yaml
INFO    src.manifest: Preparing to update appdata /home/bbhtt/Downloads/com.github.vladimiry.ElectronMail/com.github.vladimiry.ElectronMail.metainfo.xml
ERROR   src.manifest: No main source configured and no external source in /home/bbhtt/Downloads/com.github.vladimiry.ElectronMail/com.github.vladimiry.ElectronMail.yaml. Not updating appdata
INFO    src.main: Check finished with 0 error(s)
```
