### ISSUE TITLE
TestPyPIChecker is broken

### ISSUE THREAD

**Issue by wjt** [flathub-infra/flatpak-external-data-checker#441]
```
======================================================================
FAIL: test_check (tests.test_pypichecker.TestPyPIChecker.test_check)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/async_case.py", line 90, in _callTestMethod
    if self._callMaybeAsync(method) is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/async_case.py", line 112, in _callMaybeAsync
    return self._asyncioRunner.run(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/flatpak-external-data-checker/flatpak-external-data-checker/tests/test_pypichecker.py", line 39, in test_check
    self.assertRegex(
AssertionError: Regex didn't match: '[https://files.pythonhosted.org/packages/[a-f0-9/]+/PyYAML-[\\d\\.]+.(tar.(gz](https://files.pythonhosted.org/packages/[a-f0-9/]+/PyYAML-[//d//.]+.(tar.(gz)|xz|bz2)|zip)' not found in 'https://files.pythonhosted.org/packages/54/ed/79a089b6be93607fa5cdaedf301d7dfb23af5f25c398d5ead2525b063e17/pyyaml-6.0.2.tar.gz'```

**Comment by bbhtt** [comment]
Fixed by https://github.com/flathub-infra/flatpak-external-data-checker/commit/85b9d096f685cae66b9a4a9b5ca958eab62ab22d
