### ISSUE TITLE
url-template: $version_ produces error

### ISSUE THREAD

**Issue by A6GibKm** [flathub-infra/flatpak-external-data-checker#89]
When using 
```yaml
      - type: file
        dest-filename: protonmail-bridge.deb
        url: https://protonmail.com/download/protonmail-bridge_1.3.3-1_amd64.deb
        sha256: 5265f10ec78a1051ed816910f55aa8b1ebfca53f747df38dc8af27f214105ca0
        x-checker-data:
          type: html
          url: https://protonmail.com/download/current_version_linux.json
          version-pattern: protonmail-bridge_(\d.\d.\d-\d)_amd64.deb
          url-template: https://protonmail.com/download/protonmail-bridge_$version_amd64.deb
```

I get

```
flatpak run org.flathub.flatpak-external-data-checker ch.protonmail.protonmail-bridge.yaml
Traceback (most recent call last):
  File "/app/bin/flatpak-external-data-checker", line 30, in <module>
    main()
  File "/app/lib/fedc/src/main.py", line 214, in main
    manifest_checker.check(filter_type)
  File "/app/lib/fedc/src/checker.py", line 196, in check
    checker.check(data)
  File "/app/lib/fedc/src/checkers/htmlchecker.py", line 91, in check
    latest_url = Template(url_template).substitute(version=latest_version)
  File "/usr/lib/python3.7/string.py", line 132, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python3.7/string.py", line 125, in convert
    return str(mapping[named])
KeyError: 'version_amd64'
```

**Comment by wjt** [comment]
https://docs.python.org/3/library/string.html#template-strings

`_` is a valid character in template identifiers. Try:

```
          url-template: https://protonmail.com/download/protonmail-bridge_${version}_amd64.deb
```

**Comment by A6GibKm** [comment]
Thanks for the quick reply, that was it.
