### ISSUE TITLE
VueScan checker has stopped working

### ISSUE THREAD

**Issue by FakeShemp** [flathub-infra/flatpak-external-data-checker#99]
It seems the rotating url check for https://github.com/flathub/com.hamrick.VueScan have stopped working. 

Perhaps a recent update broke it or it has stopped working on the server.

**Comment by gasinvein** [comment]
Looks like it regressed after #87
For some reason f-e-d-c tries to add a release to appdata when version is `None`:
```
2020-12-28T12:38:14.8259528Z Traceback (most recent call last):
2020-12-28T12:38:14.8261189Z   File "/opt/flatpak-external-data-checker/flatpak-external-data-checker", line 30, in <module>
2020-12-28T12:38:14.8262227Z     main()
2020-12-28T12:38:14.8263315Z   File "/opt/flatpak-external-data-checker/src/main.py", line 268, in main
2020-12-28T12:38:14.8264297Z     changes = manifest_checker.update_manifests()
2020-12-28T12:38:14.8265590Z   File "/opt/flatpak-external-data-checker/src/checker.py", line 272, in update_manifests
2020-12-28T12:38:14.8266601Z     self._update_manifest(path, datas, changes)
2020-12-28T12:38:14.8267831Z   File "/opt/flatpak-external-data-checker/src/checker.py", line 263, in _update_manifest
2020-12-28T12:38:14.8269073Z     appdata, last_update.version, last_update.timestamp.strftime("%F")
2020-12-28T12:38:14.8270562Z   File "/opt/flatpak-external-data-checker/src/lib/appdata.py", line 139, in add_release_to_file
2020-12-28T12:38:14.8271591Z     add_release(appdata_path, buf, version, date)
2020-12-28T12:38:14.8272819Z   File "/opt/flatpak-external-data-checker/src/lib/appdata.py", line 134, in add_release
2020-12-28T12:38:14.8273774Z     reader.parse(in_path_or_stream)
2020-12-28T12:38:14.8274481Z   File "/usr/lib/python3.7/xml/sax/saxutils.py", line 312, in parse
2020-12-28T12:38:14.8275168Z     self._parent.parse(source)
2020-12-28T12:38:14.8275898Z   File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
2020-12-28T12:38:14.8276920Z     xmlreader.IncrementalParser.parse(self, source)
2020-12-28T12:38:14.8277945Z   File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
2020-12-28T12:38:14.8278576Z     self.feed(buffer)
2020-12-28T12:38:14.8279253Z   File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
2020-12-28T12:38:14.8279986Z     self._parser.Parse(data, isFinal)
2020-12-28T12:38:14.8280692Z   File "../Modules/pyexpat.c", line 417, in StartElement
2020-12-28T12:38:14.8281517Z   File "/usr/lib/python3.7/xml/sax/expatreader.py", line 333, in start_element
2020-12-28T12:38:14.8282494Z     self._cont_handler.startElement(name, AttributesImpl(attrs))
2020-12-28T12:38:14.8283908Z   File "/opt/flatpak-external-data-checker/src/lib/appdata.py", line 59, in startElement
2020-12-28T12:38:14.8284827Z     self._emit_release()
2020-12-28T12:38:14.8286132Z   File "/opt/flatpak-external-data-checker/src/lib/appdata.py", line 51, in _emit_release
2020-12-28T12:38:14.8287273Z     super().startElement("release", {"version": self._version, "date": self._date})
2020-12-28T12:38:14.8288195Z   File "/usr/lib/python3.7/xml/sax/saxutils.py", line 269, in startElement
2020-12-28T12:38:14.8289028Z     self._cont_handler.startElement(name, attrs)
2020-12-28T12:38:14.8289883Z   File "/usr/lib/python3.7/xml/sax/saxutils.py", line 171, in startElement
2020-12-28T12:38:14.8290798Z     self._write(' %s=%s' % (name, quoteattr(value)))
2020-12-28T12:38:14.8291541Z   File "/usr/lib/python3.7/xml/sax/saxutils.py", line 61, in quoteattr
2020-12-28T12:38:14.8292228Z     data = escape(data, entities)
2020-12-28T12:38:14.8293002Z   File "/usr/lib/python3.7/xml/sax/saxutils.py", line 27, in escape
2020-12-28T12:38:14.8293673Z     data = data.replace("&", "&amp;")
2020-12-28T12:38:14.8294595Z AttributeError: 'NoneType' object has no attribute 'replace'
```
